[build]
  command = "npx vite build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

[dev]
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "https://evshealthcare.co.uk/*"
  to = "https://www.evshealthcare.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://evshealthcare.co.uk/*"
  to = "https://www.evshealthcare.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false