export const jobs = [
  {
    id: 1,
    title: "Registered Nurse (RGN)",
    type: "Temporary / Permanent",
    location: "Preston, Lancashire",
    pay: "£18–£24/hr",
    payValue: 21,
    urgent: true,
    icon: "👩‍⚕️",
    shift: "Day & Night Shifts",
    experience: "2+ years preferred",
  },
  {
    id: 2,
    title: "Healthcare Care Assistant",
    type: "Flexible Shifts Available",
    location: "North-West England",
    pay: "£12–£15/hr",
    payValue: 13.5,
    urgent: false,
    icon: "🏥",
    shift: "Flexible Hours",
    experience: "No experience required",
  },
  {
    id: 3,
    title: "Support Worker",
    type: "Temporary / Permanent",
    location: "Preston & Surrounding",
    pay: "£11–£14/hr",
    payValue: 12.5,
    urgent: true,
    icon: "🤲",
    shift: "Weekend Availability",
    experience: "Driving license preferred",
  },
  {
    id: 4,
    title: "RMN Mental Health Nurse",
    type: "Full Time / Part Time",
    location: "Lancashire Area",
    pay: "£22–£30/hr",
    payValue: 26,
    urgent: false,
    icon: "🧠",
    shift: "Rotating Shifts",
    experience: "NMC Registered",
  },
  {
    id: 5,
    title: "Senior Carer",
    type: "Immediate Start",
    location: "North-West England",
    pay: "£14–£17/hr",
    payValue: 15.5,
    urgent: false,
    icon: "❤️",
    shift: "Day Shifts Only",
    experience: "NVQ Level 3 required",
  },
  {
    id: 6,
    title: "Domestic Worker",
    type: "Flexible Hours",
    location: "Preston, Lancashire",
    pay: "£10.50–£12/hr",
    payValue: 11.25,
    urgent: false,
    icon: "🌟",
    shift: "Morning / Afternoon",
    experience: "Basic cleaning skills",
  },
];